# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-FormValidator-Simple
version:      0.01
version_from: lib/CGI/Application/Plugin/FormValidator/Simple.pm
installdirs:  site
requires:
    CGI::Application:              3.31
    FormValidator::Simple:         0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
